# Generated by Django 4.1.7 on 2023-11-02 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('announcement_type', models.CharField(choices=[('news', 'News'), ('advertisement', 'Advertisement'), ('video', 'Video Upload')], max_length=20)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('countdown_to', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Date', models.DateField(db_index=True, null=True)),
                ('Supplier', models.CharField(db_index=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeverageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, db_index=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('about_Image', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('default', 'Select availability...'), ('available', 'Available now'), ('Out of Stock', 'Out of Stock'), ('future', myapp.models.BeverageImage.availability_description)], db_index=True, max_length=255, null=True)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.beverage')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_address', models.TextField()),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cart')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beverageimage')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payroll_number', models.CharField(db_index=True, max_length=255, null=True)),
                ('firstname', models.CharField(db_index=True, max_length=255, null=True)),
                ('middlename', models.CharField(db_index=True, max_length=255, null=True)),
                ('lastname', models.CharField(db_index=True, max_length=255, null=True)),
                ('Date_employed', models.DateField(db_index=True, null=True)),
                ('Last_date_attendance', models.DateField(db_index=True, null=True)),
                ('Basic_Salary', models.FloatField(db_index=True, max_length=255, null=True)),
                ('Allowances', models.FloatField(db_index=True, max_length=255, null=True)),
                ('Designation', models.CharField(db_index=True, max_length=255, null=True)),
                ('Performance', models.CharField(choices=[('Great', 'Great'), ('Better', 'Better'), ('Worse', 'Worse'), ('Other', 'Other. Please specify')], db_index=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_index=True, max_length=255, null=True)),
                ('lastname', models.CharField(db_index=True, max_length=255, null=True)),
                ('middlename', models.CharField(db_index=True, max_length=255, null=True)),
                ('Business_Start_Date', models.DateField(db_index=True, null=True)),
                ('Responsibility', models.CharField(db_index=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('notifications', models.BooleanField(default=True)),
                ('font_size', models.CharField(default='medium', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beverage_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.beverageimage')),
                ('items', models.ManyToManyField(to='myapp.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opening_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_Take_Date', models.DateField(blank=True, db_index=True, null=True)),
                ('Physical_balance', models.FloatField(blank=True, db_index=True, max_length=200, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beverage')),
            ],
        ),
        migrations.CreateModel(
            name='New_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchase_Date', models.DateField(blank=True, db_index=True, null=True)),
                ('Purchase_Amount', models.FloatField(blank=True, db_index=True, max_length=200, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beverage')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.contactdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, db_index=True, null=True)),
                ('Place_of_usage', models.CharField(choices=[('Internal Sales', 'Internal Sales'), ('Online Sale', 'Online Sale')], db_index=True, max_length=255, null=True)),
                ('Used_Amount', models.FloatField(blank=True, db_index=True, max_length=200, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beverage')),
            ],
        ),
        migrations.AddField(
            model_name='beverageimage',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='images', to='myapp.category'),
        ),
        migrations.CreateModel(
            name='Beverage_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(db_index=True, null=True)),
                ('Unit_Of_Measure', models.CharField(choices=[('Kg', 'Kg'), ('Ltr', 'Ltr'), ('Bag', 'Bag'), ('Pcs', 'Pcs'), ('Carton', 'Carton'), ('Pkt', 'Pkt'), ('Tons', 'Tons'), ('Bottles', 'Bottles'), ('Dose', 'Dose')], db_index=True, max_length=255, null=True)),
                ('price_ksh', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('Beverage_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beverage')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user_logout', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
