# Generated by Django 4.1.7 on 2023-09-21 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('Date', models.DateField(db_index=True, null=True)),
                ('Supplier', models.CharField(db_index=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeverageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('about_Image', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('Payroll_number', models.CharField(db_index=True, max_length=255, null=True)),
                ('firstname', models.CharField(db_index=True, max_length=255, null=True)),
                ('middlename', models.CharField(db_index=True, max_length=255, null=True)),
                ('lastname', models.CharField(db_index=True, max_length=255, null=True)),
                ('Date_employed', models.DateField(db_index=True, null=True)),
                ('Last_date_attendance', models.DateField(db_index=True, null=True)),
                ('Basic_Salary', models.FloatField(db_index=True, max_length=255, null=True)),
                ('Allowances', models.FloatField(db_index=True, max_length=255, null=True)),
                ('Designation', models.CharField(db_index=True, max_length=255, null=True)),
                ('Performance', models.CharField(choices=[('Great', 'Great'), ('Better', 'Better'), ('Worse', 'Worse'), ('Other', 'Other. Please specify')], db_index=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('firstname', models.CharField(db_index=True, max_length=255, null=True)),
                ('lastname', models.CharField(db_index=True, max_length=255, null=True)),
                ('middlename', models.CharField(db_index=True, max_length=255, null=True)),
                ('Business_Start_Date', models.DateField(db_index=True, null=True)),
                ('Responsibility', models.CharField(db_index=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='New_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchase_Date', models.DateField(blank=True, db_index=True, null=True)),
                ('Purchase_Amount', models.FloatField(blank=True, db_index=True, max_length=200, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beverage')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, db_index=True, null=True)),
                ('Place_of_usage', models.CharField(choices=[('Internal', 'Internal'), ('Online', 'Online Sale')], db_index=True, max_length=255, null=True)),
                ('Used_Amount', models.FloatField(blank=True, db_index=True, max_length=200, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beverage')),
            ],
        ),
        migrations.CreateModel(
            name='Beverage_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(db_index=True, null=True)),
                ('Unit_Of_Measure', models.CharField(choices=[('Kg', 'Kg'), ('Ltr', 'Ltr'), ('Bag', 'Bag'), ('Pcs', 'Pcs'), ('Carton', 'Carton'), ('Pkt', 'Pkt'), ('Tons', 'Tons'), ('Bottles', 'Bottles'), ('Dose', 'Dose')], db_index=True, max_length=255, null=True)),
                ('price_ksh', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('Beverage_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beverage')),
            ],
        ),
    ]
