# Generated by Django 4.1.7 on 2023-09-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employer',
            name='index',
            field=models.IntegerField(),
        ),
    ]
