# Generated by Django 4.1.7 on 2023-09-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_beverage_index_alter_employee_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='firstname',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='lastname',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='middlename',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='firstname',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='lastname',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='middlename',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Allowances',
            field=models.FloatField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Basic_Salary',
            field=models.FloatField(db_index=True, max_length=255, null=True),
        ),
    ]
