# Generated by Django 4.1.7 on 2023-09-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_beverage_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='index',
        ),
    ]
