# Generated by Django 4.1.7 on 2023-11-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_businesssettings_businesssetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssetting',
            name='business_phone',
            field=models.CharField(max_length=30),
        ),
    ]
