# Generated by Django 4.1.7 on 2023-09-21 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_employer_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_Take_Date', models.DateField(blank=True, db_index=True, null=True)),
                ('Physical_balance', models.FloatField(blank=True, db_index=True, max_length=200, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beverage')),
            ],
        ),
    ]
