# Generated by Django 5.0.4 on 2024-04-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_item_price_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='about_Image',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
