# Generated by Django 4.1.7 on 2023-09-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_employee_name_remove_employer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Payroll_nummber',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
