# Generated by Django 4.1.7 on 2023-09-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employee_payroll_nummber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Payroll_nummber',
            new_name='Payroll_number',
        ),
    ]
