# Generated by Django 4.1.7 on 2023-09-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_payroll_nummber_employee_payroll_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Responsibility',
            new_name='Designation',
        ),
        migrations.AddField(
            model_name='employee',
            name='Last_date_attendance',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Performance',
            field=models.CharField(choices=[('Great', 'Great'), ('Better', 'Better'), ('Worse', 'Worse'), ('Other', 'Other. Please specify'), ('Carton', 'Carton'), ('Pkt', 'Pkt'), ('Tons', 'Tons'), ('Bottles', 'Bottles'), ('Dose', 'Dose')], db_index=True, max_length=255, null=True),
        ),
    ]
