# Generated by Django 5.0.4 on 2024-04-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_student_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_enrollment',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
