# Generated by Django 5.0.4 on 2024-04-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_student_enrollment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_enrollment',
            name='has_smartphone_or_computer',
            field=models.BooleanField(default=False),
        ),
    ]
