# Generated by Django 4.1.7 on 2023-09-17 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_responsibility_employee_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Performance',
            field=models.CharField(choices=[('Great', 'Great'), ('Better', 'Better'), ('Worse', 'Worse'), ('Other', 'Other. Please specify')], db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beverage'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beverage'),
        ),
    ]
