# Generated by Django 4.1.7 on 2024-03-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_beverage_price_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage_price',
            name='Price_Negotiable',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
