# Generated by Django 5.0.4 on 2024-04-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_student_enrollment_has_smartphone_or_computer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_enrollment',
            old_name='has_smartphone_or_computer',
            new_name='Do_you_have_smartphone_or_computer',
        ),
    ]
