# Generated by Django 4.1.7 on 2023-09-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_employee_performance_alter_employee_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employer',
            name='index',
            field=models.IntegerField(),
        ),
    ]
