# Generated by Django 4.1.7 on 2024-03-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_product_productitem'),
        ('myapp', '0008_beverage_price_price_negotiable'),
    ]

    operations = [
    ]
