# Generated by Django 4.1.7 on 2023-09-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_daily_usage_place_of_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_usage',
            name='Place_of_usage',
            field=models.CharField(choices=[('Internal', 'Internal'), ('Online', 'Online Sale')], db_index=True, max_length=255, null=True),
        ),
    ]
