# Generated by Django 5.0.4 on 2024-04-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_item_price_unit_of_measure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('budget_in_Ksh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_customers', models.TextField()),
                ('software_type', models.CharField(choices=[('Mobile Application', 'Mobile Application'), ('Website', 'Website'), ('Desktop Application', 'Desktop Application'), ('Other', 'Other')], max_length=50)),
                ('additional_specifications', models.TextField(blank=True)),
                ('customer_type', models.CharField(choices=[('Individual', 'Individual'), ('Small Business', 'Small Business'), ('Enterprise', 'Enterprise')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
