# Generated by Django 4.1.7 on 2023-09-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_usage',
            name='Place_of_usage',
            field=models.CharField(choices=[('Internal Sales', 'Internal Sales'), ('Online Sale', 'Online Sale')], db_index=True, max_length=255, null=True),
        ),
    ]
