# Generated by Django 4.1.7 on 2023-10-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_daily_usage_place_of_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_address', models.TextField()),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
