# Generated by Django 5.0.4 on 2024-04-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_sale_alter_itemimage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sales_integer_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
