# Generated by Django 5.0.4 on 2024-04-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_sale_sales_integer_amount_alter_sale_sales_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sales_integer_amount',
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity_sold',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_amount',
            field=models.TextField(blank=True, null=True),
        ),
    ]
