# Generated by Django 4.1.7 on 2023-10-03 13:49

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_cart_cartitem_beverageimage_product_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverageimage',
            name='Date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='beverageimage',
            name='Status',
            field=models.CharField(choices=[('default', 'Select availability...'), ('available', 'Available now'), ('Out of Stock', 'Out of Stock'), ('future', myapp.models.BeverageImage.availability_description)], db_index=True, max_length=255, null=True),
        ),
    ]
