# Generated by Django 5.0.4 on 2024-05-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_product_name_sale_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='year',
            field=models.TextField(blank=True, null=True),
        ),
    ]
