# Generated by Django 4.1.7 on 2023-10-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_category_rename_status_beverageimage_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='beverage_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.beverageimage'),
        ),
    ]
