# Generated by Django 4.1.7 on 2023-10-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_details_activity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
